#!/bin/sh
#
# ~/.xprofile

# local users can connect
xhost +local:

# source base environment
. ~/.env.base

# keyboard layout
setxkbmap "us,gb" -option "grp:shifts_toggle"

# start services
xhost +si:localuser:$(whoami)
xautolock -time 10 -locker "lock-desktop" -detectsleep -corners +-00  -cornerdelay 4 -cornerredelay 4 &
dunst &
xbindkeys &
syndaemon -t -k -i 2 -d &
urxvtd -q -o -f

# pulseaudio
/usr/bin/pulseaudio --start
/usr/bin/start-pulseaudio-x11

# no beep
xset -b
