#!/bin/sh
#
# ~/.xprofile

# turn off beep
xset -b

# keyboard layout
setxkbmap "us,gb" -option "grp:shifts_toggle"

# set brightness
xbacklight -set 90

# start services
urxvtd -q -o -f
xhost +si:localuser:$(whoami)
xautolock -time 10 -locker "i3lock -i ~/background/lock -u" -detectsleep -corners +-00  -cornerdelay 4 -cornerredelay 4 &
dunst &
xbindkeys &
syndaemon -t -k -i 2 -d &
