set mouse-=a
set guifont=Andale\ Mono
set guioptions=caig
set guioptions-=LlrbtT
set mouseshape=n:beam,ve:beam,sd:updown

highlight CommandCursor guifg=white guibg=steelblue
highlight InsertCursor guifg=white guibg=red
set guicursor=n-v-c:block-CommandCursor
set guicursor+=i:ver100-InsertCursor
set guicursor+=i:blinkwait10
set guicursor+=n-v-c:blinkon0

set numberwidth=5

set spell
set spelllang=en
set spellsuggest=9

" tag list
let g:Tlist_Show_Menu=1

au GUIEnter * :call Maximize_Window()
au BufEnter * let &titlestring=expand("%:p:~")
